import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';
import type { IntegrationStatus, IntegrationTestResult } from '../integration-enums.js';

/**
 * A labelled GitHub credential slot owned by one user. Owns table
 * `integrations` (see `docs/agents/modules/integrations.md#data-model`).
 *
 * - `uuid` is generated by the application before encryption (it is part of
 *   the secret's AAD) and is the only identifier ever exposed.
 * - `userId` is a plain column, with no TypeORM relation: code never joins
 *   `auth_users`. The physical FK (`ON DELETE CASCADE`) lives only in the
 *   migration, as the documented exception to the logical-FK strategy.
 * - The secret is stored encrypted across the four `secret_*` columns and
 *   must never be serialised: responses are built from an explicit allowlist.
 */
@Entity('integrations')
@Index('idx_integrations_user_id_label_normalized', ['userId', 'labelNormalized'], { unique: true })
export class Integration {
  @PrimaryGeneratedColumn()
    id!: number;

  @Index('idx_integrations_uuid', { unique: true })
  @Column({ type: 'char', length: 36 })
    uuid!: string;

  @Index('idx_integrations_user_id')
  @Column({ name: 'user_id', type: 'int' })
    userId!: number;

  @Column({ type: 'varchar', length: 32 })
    provider!: string;

  @Column({ type: 'varchar', length: 32 })
    type!: string;

  @Column({ type: 'varchar', length: 100 })
    label!: string;

  @Column({ name: 'label_normalized', type: 'varchar', length: 100 })
    labelNormalized!: string;

  @Column({ type: 'varchar', length: 32 })
    status!: IntegrationStatus;

  @Column({ name: 'status_reason', type: 'varchar', length: 64, nullable: true })
    statusReason!: string | null;

  @Column({ name: 'github_login', type: 'varchar', length: 255 })
    githubLogin!: string;

  @Column({ name: 'expires_at', type: 'datetime', nullable: true })
    expiresAt!: Date | null;

  @Column({ name: 'last_tested_at', type: 'datetime', nullable: true })
    lastTestedAt!: Date | null;

  @Column({ name: 'last_test_result', type: 'varchar', length: 32, nullable: true })
    lastTestResult!: IntegrationTestResult | null;

  @Column({ type: 'json' })
    metadata!: Record<string, unknown>;

  @Column({ name: 'secret_hint', type: 'varchar', length: 64, nullable: true })
    secretHint!: string | null;

  @Index('idx_integrations_secret_key_id')
  @Column({ name: 'secret_key_id', type: 'char', length: 8 })
    secretKeyId!: string;

  @Column({ name: 'secret_iv', type: 'varbinary', length: 12 })
    secretIv!: Buffer;

  @Column({ name: 'secret_auth_tag', type: 'varbinary', length: 16 })
    secretAuthTag!: Buffer;

  @Column({ name: 'secret_ciphertext', type: 'blob' })
    secretCiphertext!: Buffer;

  @CreateDateColumn({ name: 'created_at' })
    createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
    updatedAt!: Date;
}
