import type { MigrationInterface, QueryRunner, TableColumnOptions } from 'typeorm';
import { Table, TableForeignKey, TableIndex } from 'typeorm';
import { createdAtColumn, idColumn, updatedAtColumn } from './helpers.js';

const TABLE_NAME = 'integrations';

const COLUMNS: TableColumnOptions[] = [
  idColumn(),
  { name: 'uuid', type: 'char', length: '36' },
  { name: 'user_id', type: 'int' },
  { name: 'provider', type: 'varchar', length: '32' },
  { name: 'type', type: 'varchar', length: '32' },
  { name: 'label', type: 'varchar', length: '100' },
  { name: 'label_normalized', type: 'varchar', length: '100' },
  { name: 'status', type: 'varchar', length: '32' },
  { name: 'status_reason', type: 'varchar', length: '64', isNullable: true },
  { name: 'github_login', type: 'varchar', length: '255' },
  { name: 'expires_at', type: 'datetime', isNullable: true },
  { name: 'last_tested_at', type: 'datetime', isNullable: true },
  { name: 'last_test_result', type: 'varchar', length: '32', isNullable: true },
  { name: 'metadata', type: 'json' },
  { name: 'secret_hint', type: 'varchar', length: '64', isNullable: true },
  { name: 'secret_key_id', type: 'char', length: '8' },
  { name: 'secret_iv', type: 'varbinary', length: '12' },
  { name: 'secret_auth_tag', type: 'varbinary', length: '16' },
  { name: 'secret_ciphertext', type: 'blob' },
  createdAtColumn(),
  updatedAtColumn(),
];

export const INTEGRATIONS_INDEXES: TableIndex[] = [
  new TableIndex({ name: 'idx_integrations_uuid', columnNames: ['uuid'], isUnique: true }),
  new TableIndex({
    name: 'idx_integrations_user_id_label_normalized',
    columnNames: ['user_id', 'label_normalized'],
    isUnique: true,
  }),
  new TableIndex({ name: 'idx_integrations_user_id', columnNames: ['user_id'] }),
  new TableIndex({ name: 'idx_integrations_secret_key_id', columnNames: ['secret_key_id'] }),
];

/**
 * Physical FK from `integrations.user_id` to `auth_users.id`, `ON DELETE CASCADE`.
 *
 * This is the **deliberate, documented exception** to the project's logical-FK-only
 * database strategy (docs/agents/modules/integrations.md#owner-foreign-key): a stored
 * GitHub credential must never outlive its owner, so the database removes a user's
 * integrations even if a future user-deletion path forgets to notify the Integrations
 * module. It is the only physical cross-module FK; code still never joins `auth_users`.
 */
export const INTEGRATIONS_OWNER_FK = new TableForeignKey({
  name: 'fk_integrations_user_id',
  columnNames: ['user_id'],
  referencedTableName: 'auth_users',
  referencedColumnNames: ['id'],
  onDelete: 'CASCADE',
});

/**
 * Creates the Integrations module's `integrations` table: one labelled, encrypted GitHub
 * credential slot per row (see docs/agents/modules/integrations.md#data-model). The
 * secret is stored across `secret_key_id`/`secret_iv`/`secret_auth_tag`/
 * `secret_ciphertext`; `uuid` is generated by the application. `down` drops the
 * table, and the FK with it.
 */
export class IntegrationsCreateIntegrations20261002120011 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(new Table({ name: TABLE_NAME, columns: COLUMNS }), true);

    for (const index of INTEGRATIONS_INDEXES) {
      await queryRunner.createIndex(TABLE_NAME, index);
    }

    await queryRunner.createForeignKey(TABLE_NAME, INTEGRATIONS_OWNER_FK);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable(TABLE_NAME);
  }
}
